spring:
  application:
    name: clinic-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

application:
  config:
    admin-specialization-url: http://${APPLICATION_CONFIG_DOCTORSERVICE:localhost:8222}/api/v1/server/specializations