spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: Asia/Ho_Chi_Minh
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appointment_db}
    username: postgres
    password: postgres
  kafka:
    consumer:
      group-id: appointment-group
      auto-offset-reset: earliest
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          specialization-info:com.nhom1.appointment_service.kafka.specialization.SpecializationInfo,
          clinic-info:com.nhom1.appointment_service.kafka.clinic.ClinicInfo,
          schedule-info:com.nhom1.appointment_service.kafka.schedule.ScheduleInfo,
          shift-info:com.nhom1.appointment_service.kafka.schedule.ShiftInfo
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

server:
  port: 8073
  servlet:
    context-path: /api/v1

application:
  config:
    appointment-time: 15
    doctor-url: ${APPLICATION_CONFIG_DOCTORSERVICE:http://localhost:8222}/api/v1/server/doctors
    clinic-url: ${APPLICATION_CONFIG_CLINICSERVICE:http://localhost:8222}/api/v1/server/clinics
    schedule-url: ${APPLICATION_CONFIG_SHIFTSERVICE:http://localhost:8222}/api/v1/server/schedules