server:
  port: 8070
  servlet:
    context-path: /api/v1

spring:
  datasource:
    username: postgres
    password: postgres
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/doctor_db}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAPSERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.type.mapping: 
        specialization-info: com.nhom1.doctor_service.kafka.SpecializationInfo
        doctor-info: com.nhom1.doctor_service.kafka.DoctorInfo
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}