server:
  port: 8070
  servlet:
    context-path: /api/v1

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/doctor_db
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true