spring:
  cloud:
    gateway:
      discovery:
          locator:
            enabled: true
      routes:
        - id: specialization-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api/v1/specializations/**
        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api/v1/doctors/**
        - id: admin-doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api/v1/admin/doctors/**
        - id: admin-specialization-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api/v1/admin/specializations/**
        - id: server-doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api/v1/server/doctors/**
        - id: server-specialization-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api/v1/server/specializations/**
        - id: admin-clinic-service
          uri: lb://CLINIC-SERVICE
          predicates:
            - Path=/api/v1/admin/clinics/**
        - id: clinic-service
          uri: lb://CLINIC-SERVICE
          predicates:
            - Path=/api/v1/clinics/**
        - id: server-clinic-service
          uri: lb://CLINIC-SERVICE
          predicates:
            - Path=/api/v1/server/clinics/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

server:
  port: 8222
