spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shift_db}
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

server:
  port: 8072
  servlet:
    context-path: /api/v1

application:
  config:
    doctor-url: ${APPLICATION_CONFIG_DOCTORSERVICE:http://localhost:8222}/api/v1/server/doctors
    clinic-url: ${APPLICATION_CONFIG_CLINICSERVICE:http://localhost:8222}/api/v1/server/clinics